import contract from 'truffle-contract';
import DAuctionsAbi from '../../build/contracts/DAuctions.json';
import web3 from '../controllers/web3';

// This file is generated by the Solidity compiler to easily interact with the contract.

let DAuctions = contract(DAuctionsAbi);
DAuctions.setProvider(web3.currentProvider);

export default DAuctions;
