import contract from 'truffle-contract';
import UserAbi from '../../build/contracts/User.json';
import web3 from '../controllers/web3';

// This file is generated by the Solidity compiler to easily interact with the contract.

let User = contract(UserAbi);
User.setProvider(web3.currentProvider);

export default User;
