import contract from 'truffle-contract';
import UserAbi from '../../build/contracts/Users.json';
import web3 from '../controllers/web3';

// This file is generated by the Solidity compiler to easily interact with the contract.

let Users = contract(UserAbi);
Users.setProvider(web3.currentProvider);

export default Users;
